---
version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks: ['stack']

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports: ['5601:5601']
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #   - "8081:80"
  #   - "8882:8882"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx.site:/etc/nginx/sites-enabled/default
  #   links: ['kibana']
  #   depends_on: ['elasticsearch','kibana']
networks:
  stack: {}
